# Generated by Django 5.1.2 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('production', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson1_test_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test_table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('production_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lesson1_test_table2',
                'managed': False,
            },
        ),
    ]
